# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ycdEq_U3KB6pMs6VQpuE7OLE4i72Ozpw

# Importing Key Modules
"""

import pandas as pd
import numpy as np

"""# Link to Kaggle Project"""

! pip install -q kaggle

from google.colab import files
files.upload()

! mkdir ~/.kaggle

! cp kaggle.json ~/.kaggle/

! chmod 600 ~/.kaggle/kaggle.json

#! kaggle competitions download -c 'name-of-competition'
! kaggle competitions download -c 'm5-forecasting-accuracy'

"""### Unzip Data"""

! mkdir train

! unzip sales_train_evaluation.csv 
! unzip sell_prices.csv

"""### Load Data"""

sales = pd.read_csv('sales_train_evaluation.csv')
sales.name = 'sales'
calendar = pd.read_csv('calendar.csv')
calendar.name = 'calendar'
prices = pd.read_csv('sell_prices.csv')
prices.name = 'prices'

"""Since, the validation data is now available for the days 1914-1941, Adding zero sales for days: d_1942 - d_1969(Test"""

#Add zero sales for the remaining days 1942-1969
for d in range(1942,1970):
    col = 'd_' + str(d)
    sales[col] = 0
    sales[col] = sales[col].astype(np.int16)

